### ISSUE TITLE
Question about public keys dataset

### ISSUE THREAD

**Issue by FrancescoBonizzi** [giuseppeM99/GreenPassVerifyBot#4]
Hi Giuseppe and thanks a lot for your repo!

I didn't understand a thing: in update-dataset.sh it seems that the exposed public keys come from a Netherlands API. 

1. Are those keys related only to NL green passes or for all Europe? I tested your bot with my italian green pass and it says it's valid!
2. If not, do you know an italian public API for the keys?

Thanks a lot.

**Comment by giuseppeM99** [comment]
Hi Francesco, the NL keyset comes from the python example from the European eHealth Network's repo ([link](https://github.com/ehn-dcc-development/ehn-sign-verify-python-trivial/blob/aed91e15d58ad10441568e4810b715dadcad74b5/hc1_verify.py#L33))
the NL API should expose all the public keys accepted by the EU

The Italian Ministry of Health has its own API and the documentation is available [here (code)](https://github.com/ministero-salute/it-dgc-documentation/blob/master/openapi.yaml) and [here (website)](https://eu-digital-green-certificates.github.io/dgc-gateway/)

I use the NL API as i can download the whole dataset from a single request, if you wish here's a python script to download the certificates from the Italian API (thanks @Knocks83)
```python3
from requests import get

BASE_URL = "https://get.dgc.gov.it/v1/dgc"

def getCertificates(base_url):
    certificates = []
    counter = 0
    while True:
        cert = get(url=base_url+"/signercertificate/update", headers={'X-RESUME-TOKEN': str(counter)})
        res = cert.text
        if res != "":
            certificates.append(res)
        else:
            return certificates
        counter = cert.headers['X-RESUME-TOKEN']

print(getCertificates(BASE_URL))
```

Hope that I've answered to your questions, if you have any further feel free to ask

**Comment by FrancescoBonizzi** [comment]
Thanks a lot, you answered my question! 😃
